dist: trusty
sudo: required

before_install:
  - echo "deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
  - curl https://bazel.build/bazel-release.pub.gpg | sudo apt-key add -
  - sudo apt-get update && sudo apt-get -y install bazel
  - sudo apt-get upgrade bazel


script:
  - bazel test //src/...

# matrix:
#   include:
#     - language: java
#       jdk:
#         - oraclejdk8
#         - openjdk8
#       before_cache:
#         - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
#         - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
#       cache:
#         directories:
#         - $HOME/.gradle/caches/
#         - $HOME/.gradle/wrapper/
