language: java
jdk: openjdk8

stages:
  - lint
  - test

addons:
  apt:
    sources:
      - sourceline: "deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8"
        key_url: "https://storage.googleapis.com/bazel-apt/doc/apt-key.pub.gpg"
    packages:
      - bazel

install: |-
  cp tools/ci/.bazelrc $HOME

jobs:
  include:
    # lint
    - stage: lint
      script: |-
        bazel build //third_party:google_java_format \
        && ./bazel-bin/third_party/google_java_format --version \
        && ./bazel-bin/third_party/google_java_format \
          --dry-run \
          --set-exit-if-changed \
          `find . -iname "*.java"`
    # test
    - stage: test
      script: |-
        bazel test //...
