language: java
jdk: openjdk8

stages:
  - lint
  - test

addons:
  apt:
    sources:
      - sourceline: "deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8"
        key_url: "https://storage.googleapis.com/bazel-apt/doc/apt-key.pub.gpg"
    packages:
      - bazel

install:
  - cp tools/ci/.bazelrc $HOME
  - go get -u github.com/bazelbuild/buildifier/buildifier

before_script:
  - bazel info

jobs:
  include:
    # lint
    - stage: lint
      # Google Java Format
      script:
        - bazel build //third_party:google_java_format
        - ./bazel-bin/third_party/google_java_format --version
        - ./bazel-bin/third_party/google_java_format --dry-run --set-exit-if-changed $(find . -iname "*.java" -type f)
      # Buildifier
    - script:
      - buildifier -mode=check $(find . -name BUILD -type f)
      - buildifier -mode=check $(find . -name WORKSPACE -type f)
    # test
    - stage: test
      script: |-
        bazel test //...
